import 'package:kyism/Model/model.dart';

  List<House> houseObject = [
    House(value:0, name:"House"),
    House(value:1, name:"Antres"),
    House(value:2, name:"Vega"),
    House(value:3, name:"Canopus"),
    House(value:4,name: "Algol"),
    House(value:5, name:"Bellatrix"),
    House(value:6,name: "Rigel"),
    House(value:7, name:"Altair"),
    House(value:8, name:"Sirius")
  ];

  List<GeoState> geoStateObject =[
      GeoState(value:0,name:"State"),
      GeoState(value:1,name:"Andhra Pradesh"),
      GeoState(value:2,name:"Arunachal Pradesh"),
      GeoState(value:3,name:"Assam"),
      GeoState(value:4,name:"Bihar"),
      GeoState(value:5,name:"Chhattisgarh"),
      GeoState(value:6,name:"Goa"),
      GeoState(value:7,name:"Gujarat"),
      GeoState(value:8,name:"Haryana"),
      GeoState(value:9,name:"Himachal Pradesh"),
      GeoState(value:10,name:"Jharkhand"),
      GeoState(value:11,name:"Karnataka"),
      GeoState(value:12,name:"Kerala"),
      GeoState(value:13,name:"Madhya Pradesh"),
      GeoState(value:14,name:"Maharashtra"),
      GeoState(value:15,name:"Manipur"),
      GeoState(value:16,name:"Meghalaya"),
      GeoState(value:17,name:"Mizoram"),
      GeoState(value:18,name:"Nagaland"),
      GeoState(value:19,name:"Odisha"),
      GeoState(value:20,name:"Punjab"),
      GeoState(value:21,name:"Rajasthan"),
      GeoState(value:22,name:"Sikkim"),
      GeoState(value:23,name:"Tamil Nadu"),
      GeoState(value:24,name:"Telangana"),
      GeoState(value:25,name:"Tripura"),
      GeoState(value:26,name:"Uttar Pradesh"),
      GeoState(value:27,name:"Uttarakhand"),
      GeoState(value:28,name:"West Bengal"),
      GeoState(value:29,name:"Andaman and Nicobar Islands"),
      GeoState(value:30,name:"Chandigarh"),
      GeoState(value:31,name:"Dadra and Nagar Haveli and Daman and Diu"),
      GeoState(value:32,name:"Delhi"),
      GeoState(value:33,name:"Jammu and Kashmir"),
      GeoState(value:34,name:"Ladakh"),
      GeoState(value:35,name:"Lakshadweep"),
      GeoState(value:36,name:"Puducherry")
  ];

  List<Branch> branchObject =[
      Branch(value:0,name:"Branch"),
      Branch(value:1,name:"Mining Engineering"),
      Branch(value:2,name:"Chemical Engineering"),
      Branch(value:3,name:"Civil Engineering"),
      Branch(value:4,name:"Computer Science"),
      Branch(value:5,name:"Electrical Engineering"),
      Branch(value:6,name:"Electronics and Communication Engineering"),
      Branch(value:7,name:"Electronics and Instrumentation Engineering"),
      Branch(value:8,name:"Engineering Physics"),
      Branch(value:9,name:"Environmental Science and Engineering"),
      Branch(value:10,name:"Mechanical Engineering"),
      Branch(value:11,name:"Mineral Engineering"),
      Branch(value:12,name:"Mining Machinery Engineering"),
      Branch(value:13,name:"Applied Geology"),
      Branch(value:14,name:"Applied Geophysics"),
      Branch(value:15,name:"Mathematics & Computing")
  ];


  List<Club> clubObject = [
      Club(value:0,name:"Club"),
      Club(value:1,name:"Abhay Dramatics Club"),
      Club(value:2,name:"Arka"),
      Club(value:3,name:"Artfreaks"),
      Club(value:4,name:"Book Club"),
      Club(value:5,name:"चयनिका संघ"),
      Club(value:6,name:"Cyberlabs"),
      Club(value:7,name:"E-Cell"),
      Club(value:8,name:"Fotofreaks"),
      Club(value:9,name:"name:Legends In The Making"),
      Club(value:10,name:"Lights Camera ISM (LCI)"),
      Club(value:11,name:"Literature Club (LitC)"),
      Club(value:12,name:"Manthan"),
      Club(value:13,name:"Mechismu"),
      Club(value:14,name:"Mic Drop Toastmasters"),
      Club(value:15,name:"Quiz Club IIT (ISM)"),
      Club(value:16,name:"RoboISM"),
      Club(value:17,name:"Rhythm Club"),
      Club(value:18,name:"Udaan"),
      Club(value:19,name:"We The Crew"),
      Club(value:20,name:"Fast Forward India"),
      Club(value:21,name:"Kartavya"),
      Club(value:22,name:"Mailer Daemon") 

  ];